deric/puppet-mesos

manifests/repo.pp
manifests/slave.pp

I needed to do this on RHEL6 and RHEL7 systems, so I added in the RHEL repos as valid options.  Unfortunately, the repo RPM package releases are hard-coded since the RPM to install the repo is not named ideally and does not have an alias like "latest" on the mesosphere repo, but it works well in my tests.

RHEL repo addition

---

README.md

Replace 'cgroups' with 'cgroups/cpu,cgroups/mem'.

Fix readme: isolation 'cgroups' is depricated

---

README.md
manifests/service.pp

I need the possibility to omitt the servce resource definition completely.
Our wrapper handling services is creating a custom service resource using monit etc.
For some special reasons, I'm not able to write a monit service provider I could reach into this class.

Allow omitting service resource

---

.travis.yml
Gemfile

Fix Gemfile to use PUPPET_VERSION environment variable. Restrict Puppet to < 4.0. Add testing for Puppet 3.6.2 and 3.7.5.
Tests on Travis were not honoring the requested Puppet version, as the Gemfile was not using the PUPPET_VERSION environment variable. Puppet 4.0 was added to Gem, which has breaking changes.

Fix Travis-CI

---

README.md
manifests/config.pp
manifests/init.pp
spec/classes/config_spec.rb

/etc/mesos/zk is not necessary for mesos-master or mesos-slave, and this module already adds ZK="<zk URL(s)>" to /etc/default/mesos-master and MASTER="<zk URL(s)>" to /etc/default/mesos-slave - which is what Mesos ends up using. /etc/mesos/zk, on the other hand, is hardcoded in the Marathon framework to be used. I have created a module to configure Marathon, and I am having it manage /etc/mesos/zk.
This PR adds a parameter to the deric-mesos module to enable/disable management of /etc/mesos/zk by this module. This parameter, manage_zk_file, defaults to true to maintain backwards compatibility for users of the module.
This aim of this PR, and associated discussion, can be found at PR https://github.com/deric/puppet-mesos/pull/31

Added manage_zk_file parameter, tests, and documentation.

---

manifests/config.pp
manifests/slave.pp

`use_syslog` option was implemented in the slave.pp, but it should be configured in config.pp?

Fix use_syslog option for default.erb template

---

manifests/repo.pp
spec/classes/repo_spec.rb

Found the following error when enabling mesosphere.io repository for Debian/Ubuntu:
```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: Failed to fetch http://repos.mesosphere.io/ubuntu/dists/trusty/InRelease
Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)
```
In fact, and according to official documentation https://open.mesosphere.com/getting-started/datacenter/install/, only the binary package repository should be added.

Source package repository shouldn't be added for Debian/Ubuntu

---

manifests/repo.pp

Puppetlabs-apt 2.0.0 broke apt::source https://github.com/puppetlabs/puppetlabs-apt/blob/master/CHANGELOG.md#2015-04-07---supported-release-200 this PR updates the apt::source so it works.

Update incompatible changes of puppetlabs-apt 2.0.0

---

manifests/repo.pp
spec/classes/repo_spec.rb

I've been experiencing a lot of timeouts when using `subkeys.pgp.net` as the public GPG key server for the 'Debian' osfamily. I would propose to move to `keyserver.ubuntu.com`, I find it a much more reliable key server.

Moving to a more reliable public GPG key server for 'Debian' osfamily

---

manifests/service.pp

ensure shouldn't bring master up if $enable is set to false.

The enable flag should be aligned with ensure.

---

manifests/repo.pp

If a new repo is installed, it should do an apt-get update before trying to install or will fail until a second puppet run it's issued:
```
Notice: Compiled catalog for mesosmaster1 in environment production in 0.50 seconds
Notice: /Stage[main]/Mesos::Repo/Apt::Source[mesosphere]/Apt::Setting[list-mesosphere]/File[/etc/apt/sources.list.d/mesosphere.list]/ensure: created
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install mesos' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package mesos is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```
I don't know if in RHEL/CentOS have the same problem.

Force an apt-get update before trying to install packages

---

lib/puppet/parser/functions/mesos_hash_parser.rb
manifests/master.pp
manifests/slave.pp
spec/functions/mesos_hash_parser_spec.rb

There is a conflict between mesos::property resource names when
mesos::master::options and mesos::slave::options are used on same
machine. The file is different since the directory is different but
the resource name is just the key. There is also a potential conflict
between attributes and resources names.
The solution is to add prefix to name like is done for the static
properties. This involves adding parameter to mesos_hash_parser
function.

Separate mesos master and slave options

---

.gitignore
manifests/property.pp
spec/defines/property_spec.rb

split into integer/float in specs can go away but i don't trust puppet being very coherent in future.
vendor/gems in .gitignore mainly there for convenience, it is default path bundler install suggests.

fix compiler error when property is numeric (in future parser)

---

README.md
manifests/master.pp
manifests/slave.pp
spec/classes/master_spec.rb
spec/classes/slave_spec.rb

This changes allows setting credentials for mesos master and slave as well as acls for mesos master in json format.
Note, that mesos <0.26 reads secrets as base64 encoded byte array, mesos >=0.26 reads secrets as plain strings.
This is irrelevant, if authentication is used for slaves only. It's important for framework authentication though.

support credentials and acls

---

manifests/init.pp
manifests/install.pp
manifests/master.pp
spec/classes/init_spec.rb
spec/classes/install_spec.rb

The mesos rpm for RHEL6 ships upstart service definitions.
This leads to enabled service on any machine the RPM is installed, even if the package is installed only to install the libmesos.so.
By setting `mesos::force_provider` to `none` these upstart files are removed on RHEL6 machines.

remove upstart service definition shipped with rpm for RHEL 6

---

manifests/master.pp
manifests/property.pp
manifests/slave.pp
spec/defines/property_spec.rb

Without this, the `owner` and `group` parameters for the config are not much use as they only apply to some of the files.
I don't think many users are changing the owner/group from root but this at least makes it possible to do.

Add owner and group parameters to mesos::property

---

manifests/repo.pp
spec/classes/repo_spec.rb

There were cases when the Mesos package was being installed before apt-get update had run, requiring the user to make the dependency explicit. This (hopefully) fixes that by cleaning up/correcting some of the apt stuff in `mesos::repo`.
* `include apt` shouldn't conflict with previously defined inclusions (no need to check if class defined)
* Doing `include apt` includes `apt::update`
* Doing `include apt::update` doesn't ensure any ordering of when the class is applied
* Use anchors to *contain* `Class['apt::update']` to ensure that if a resource requires `Class['mesos::repo']` by extension it also requires `Class['apt::update']`

Ensure apt-get update runs before installing Mesos package

---

manifests/service.pp

This PR make sure the mesos services are restarted on new mesos package installations, when you specify a new mesos version for example.
cc @deric 
Thanks

Restart the mesos services on new mesos package installations

---

README.md
manifests/master.pp
manifests/property.pp
manifests/slave.pp
spec/classes/master_spec.rb
spec/classes/slave_spec.rb
spec/defines/property_spec.rb

The `require` and `notify` parameters of the files created by `mesos::property` are not currently being tested and if you try to test them then things break...
Two observations with the `file` resource in `mesos::property`:
* The `require` is not necessary as Puppet will autorequire parent directories.
* The `notify => $service` is not necessary either. If we use `notify` on the `mesos::property` resource rather it does the same thing... if any of the resources in the defined type refresh, the defined type itself will refresh and notify other resources.
This PR makes changes one-by-one to:
* Remove the `require` on the file in `mesos::property`.
* Default the `service` parameter in `mesos::property` to `undef` so that the parameter is no longer required.
* Deprecate the `service` …

mesos::property require/notify fixes

---

manifests/config.pp
manifests/init.pp
manifests/service.pp
spec/classes/config_spec.rb

* Allow writing mesos::conf_file to some different place than /etc/default/mesos
* The dependencies to mesos::master/slave::conf_file is already handled in master.pp/slave.pp

Fix dependencies when setting mesos::master/slave::conf_file

---

README.md
manifests/property.pp
spec/defines/property_spec.rb

The current method of setting `value` to an empty value for `mesos::property` resources in order to remove the created file has the limitation that it doesn't work for boolean values. Also, it's not the most intuitive way of doing things.
This PR:
* Introduces an `ensure` parameter for `mesos::property` that gets passed through to the underlying `file` resource if it is set.
* Deprecates the old method of setting `value` to an empty value.
* Maintains the existing behaviour if `ensure` is not set.

Add ensure parameter to mesos::property

---

manifests/master.pp
manifests/slave.pp

* master and slave services should subscribe to
/etc/defaults/mesos-master and /etc/defaults/mesos-slave
instead of just requirering them. So the services will
restart if these files are changed.

Make mesos services subscribe to configs

---

manifests/master.pp
spec/classes/master_spec.rb

Mesos master said: "Specifying an absolute filename
to read a command line option out of without using
'file:// is deprecated and will be removed in a future
release. Simply adding 'file://' to the beginning of
the path should eliminate this warning."

Add file:// to credentials option

---

templates/master.erb

This is to allow for standalone mesos install

Make zookeeper optional

---

.gitignore
.rspec
TODO.md
manifests/params.pp
manifests/property.pp
spec/classes/cli_spec.rb
spec/classes/config_spec.rb
spec/classes/init_spec.rb
spec/classes/install_spec.rb
spec/classes/master_spec.rb
spec/classes/repo_spec.rb
spec/classes/slave_spec.rb
spec/defines/property_spec.rb
spec/defines/service_spec.rb
spec/spec_helper.rb

* Add newline character to the end of a property value.
It doesn't mess with values because options are used
as the command line arguments by the shell
* Refactored property definition with the cleaner code.
There is no need to treat numeric values differently,
set default ensure, use pick functions and defaults
from the params class.
* Rewrite property spec and some other fixes
* Add todo file

Refactor mesos::property and its spec

---

manifests/slave.pp

Fix issue with rpmnew file
mesos-slave[23463]: Failed to load unknown flag 'work_dir.rpmnew'

Install the package before managing the $conf_dir for slave

---

manifests/master.pp
manifests/slave.pp

Hi!
This pull request adds notifiers from `credentials_file` and `acls_file` to services.
Determining whether authorization or authentication is enabled is done during the start of the service e.g., through the `--credentials` option.
Then, the service reads the corresponding files. For example, you can see the system call that took place when the `mesos-master` fires up.
```
6112  open("/etc/mesos/master-credentials", O_RDONLY|O_CLOEXEC) = 7
6112  ioctl(7, TCGETS, 0x7ffc30844c60)  = -1 ENOTTY (Inappropriate ioctl for device)
6112  read(7, "{\"credentials\":[{\"principal\":\"some-principal\",\"secret\":\"some-secret\"}]}", 4096) = 71
6112  read(7, "", 4025)                 = 0
6112  read(7, "", 4096)                 = 0
6112  close(7)                          = 0
```
I would expect that …

Adds notifier from credentials and acls files to services
